### ISSUE TITLE
Find and Replace error

### ISSUE THREAD

**Issue by epi-clz** [Epiconcept-Paris/STRAP-epiuf#109]
Hello @epi-gde 

I found in line 237 in R/utilsFiles.R that there might be an error:

 ReplaceWord <- ifelse((length(replacement<= i)),replacement[i],replacement[1])
 
 The correct way would be
 
 ReplaceWord <- ifelse(length(replacement)<= i,replacement[i],replacement[1])
 
 Let me know

**Comment by epi-gde** [comment]
That's the incredible R language... this is not what I wanted but it runs !
Because (replacement <= i) return a vector filled with TRUE/FALSE on the same length than replacement !  
It runs but it would give wrong result if we try to more than one replacement, because the first will always be used 
I add a test for that and I make the change ;)

**Comment by epi-gde** [comment]
Test added, vignette changed, check passed
